id: P000777
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2CZ8068
  title: བྱང་ཆུབ་བདེ་ལམ་གྱི་ཟིན་བྲིས་ཡང་གསལ་སྒྲོན་མེ
  author: ''
  volumes:
    cc1896e765f44bacafd868b41d565d65:
      image_group_id: I1PD96644
      title: ''
      volume_number: 1
      total_pages: 46
      base_file: v001.txt
